### ISSUE TITLE
Gauntlet with lock side

### ISSUE THREAD

**Issue by shapiro85** [fsmosca/combat#3]
Hi Fsmosca,
Thank you for this useful Tournament Manager
I hope you are doing very well.
Friendly Request, Could you please add Gauntlet Tournament with option 1 engine always plays white or black (without players swapping sides)

**Comment by fsmosca** [comment]
Not really a gauntlet but combat v1.1 can already do what you described but using only 2 engines.
eng_file2 always plays white while eng_file1 always plays black.
Also set the following:
`reverse_start_side = False`

Better use cutechess-cli, it might take some time for me to implement the gauntlet in combat.

**Comment by shapiro85** [comment]
Thank you for the reply,
I am looking forward to the next update
